-- RELPPS COSMÉTICOS — Supabase
-- Rode este SQL no SQL Editor do projeto novo.
-- A tabela "enderecos" (sem acento) é a principal. A aplicação também
-- consegue ler a tabela antiga "endereços" caso ela já exista.

create table if not exists public.perfis (
  id uuid primary key references auth.users(id) on delete cascade,
  nome_completo text not null default '',
  cpf text,
  whatsapp text,
  email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.enderecos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  cep text,
  endereco text,
  numero text,
  complemento text,
  bairro text,
  cidade text,
  uf text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.perfis enable row level security;
alter table public.enderecos enable row level security;

drop policy if exists "Cliente pode ver seu perfil" on public.perfis;
create policy "Cliente pode ver seu perfil" on public.perfis for select to authenticated using (auth.uid() = id);
drop policy if exists "Cliente pode criar seu perfil" on public.perfis;
create policy "Cliente pode criar seu perfil" on public.perfis for insert to authenticated with check (auth.uid() = id);
drop policy if exists "Cliente pode atualizar seu perfil" on public.perfis;
create policy "Cliente pode atualizar seu perfil" on public.perfis for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "Cliente pode ver seus enderecos" on public.enderecos;
create policy "Cliente pode ver seus enderecos" on public.enderecos for select to authenticated using (auth.uid() = user_id);
drop policy if exists "Cliente pode criar endereco" on public.enderecos;
create policy "Cliente pode criar endereco" on public.enderecos for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "Cliente pode atualizar endereco" on public.enderecos;
create policy "Cliente pode atualizar endereco" on public.enderecos for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Cliente pode excluir endereco" on public.enderecos;
create policy "Cliente pode excluir endereco" on public.enderecos for delete to authenticated using (auth.uid() = user_id);

grant select, insert, update on public.perfis to authenticated;
grant select, insert, update, delete on public.enderecos to authenticated;

-- ===== CLUBE RELPPS+ =====
-- Execute esta parte também no Supabase quando quiser persistir o programa de fidelidade na nuvem.
create table if not exists public.clube_relpps (
  user_id uuid primary key references auth.users(id) on delete cascade,
  pontos integer not null default 0,
  boas_vindas_concedidas boolean not null default false,
  nivel text not null default 'Essencial',
  updated_at timestamptz not null default now()
);

create table if not exists public.clube_relpps_cupons (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  codigo text not null unique,
  valor numeric(10,2) not null,
  usado boolean not null default false,
  created_at timestamptz not null default now(),
  used_at timestamptz
);

alter table public.clube_relpps enable row level security;
alter table public.clube_relpps_cupons enable row level security;

drop policy if exists "Cliente pode ver seu clube" on public.clube_relpps;
create policy "Cliente pode ver seu clube" on public.clube_relpps for select to authenticated using (auth.uid() = user_id);
drop policy if exists "Cliente pode criar seu clube" on public.clube_relpps;
create policy "Cliente pode criar seu clube" on public.clube_relpps for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "Cliente pode atualizar seu clube" on public.clube_relpps;
create policy "Cliente pode atualizar seu clube" on public.clube_relpps for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Cliente pode ver seus cupons do clube" on public.clube_relpps_cupons;
create policy "Cliente pode ver seus cupons do clube" on public.clube_relpps_cupons for select to authenticated using (auth.uid() = user_id);
drop policy if exists "Cliente pode criar seus cupons do clube" on public.clube_relpps_cupons;
create policy "Cliente pode criar seus cupons do clube" on public.clube_relpps_cupons for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "Cliente pode atualizar seus cupons do clube" on public.clube_relpps_cupons;
create policy "Cliente pode atualizar seus cupons do clube" on public.clube_relpps_cupons for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ===== PEDIDOS ONLINE RELPPS =====
-- Esta tabela é usada apenas pelo backend (service_role). Não exponha a service_role key no navegador.
create table if not exists public.relpps_orders (
  id text primary key,
  status text not null default 'AWAITING_PAYMENT',
  payment_status text not null default 'AWAITING_PAYMENT',
  payment_method text not null,
  customer jsonb not null default '{}'::jsonb,
  delivery jsonb not null default '{}'::jsonb,
  items jsonb not null default '[]'::jsonb,
  totals jsonb not null default '{}'::jsonb,
  discounts jsonb not null default '{}'::jsonb,
  bling_order_id bigint,
  mp_preference_id text,
  mp_payment_id text,
  infinitepay_transaction_nsu text,
  infinitepay_invoice_slug text,
  infinitepay_receipt_url text,
  payment_url text,
  error_message text,
  raw jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  paid_at timestamptz
);

create index if not exists relpps_orders_bling_order_id_idx on public.relpps_orders (bling_order_id);
create index if not exists relpps_orders_mp_preference_id_idx on public.relpps_orders (mp_preference_id);
create index if not exists relpps_orders_mp_payment_id_idx on public.relpps_orders (mp_payment_id);
create index if not exists relpps_orders_infinitepay_transaction_idx on public.relpps_orders (infinitepay_transaction_nsu);
create index if not exists relpps_orders_created_at_idx on public.relpps_orders (created_at desc);

alter table public.relpps_orders enable row level security;
-- Sem policies para anon/authenticated: leitura e escrita passam pelo backend com service_role.

-- Se a tabela já existir, execute também:
alter table public.relpps_orders add column if not exists infinitepay_transaction_nsu text;
alter table public.relpps_orders add column if not exists infinitepay_invoice_slug text;
alter table public.relpps_orders add column if not exists infinitepay_receipt_url text;

-- OAuth do Bling em produção (uma única conexão por loja).
create table if not exists public.relpps_bling_oauth (
  id integer primary key check (id = 1),
  access_token text,
  refresh_token text,
  token_type text default 'Bearer',
  expires_in integer,
  expires_at timestamptz,
  updated_at timestamptz not null default now()
);
alter table public.relpps_bling_oauth enable row level security;
