const http=require('http'),fs=require('fs'),path=require('path'); const {URL}=require('url');
const ROOT=__dirname, PORT=Number(process.env.PORT||10000), HOST=process.env.HOST||'0.0.0.0';
function loadEnv(file=path.join(ROOT,'.env')){if(!fs.existsSync(file))return;for(const line of fs.readFileSync(file,'utf8').split(/\r?\n/)){const m=line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/);if(!m||process.env[m[1]])continue;let v=m[2].trim();if((v.startsWith('"')&&v.endsWith('"'))||(v.startsWith("'")&&v.endsWith("'")))v=v.slice(1,-1);process.env[m[1]]=v;}}
loadEnv();
const handlers={bling:require('./backend/bling').handler,checkout:require('./backend/checkout').handler,shipping:require('./backend/shipping').handler,homologacao:require('./backend/bling-homologacao').handler};
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.json':'application/json; charset=utf-8','.ico':'image/x-icon','.webp':'image/webp','.gif':'image/gif'};
function body(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>2e6)req.destroy();});req.on('end',()=>resolve(b));req.on('error',reject);});}
function send(res,out){res.writeHead(out.statusCode||200,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...(out.headers||{})});res.end(out.body||'');}
async function invoke(name,req,res,url){if(req.method==='OPTIONS'){res.writeHead(204);return res.end();}const event={httpMethod:req.method,headers:req.headers,queryStringParameters:Object.fromEntries(url.searchParams.entries()),body:await body(req)||null,isBase64Encoded:false};return send(res,await handlers[name](event));}
function stat(req,res,url){let p;try{p=decodeURIComponent(url.pathname)}catch{return send(res,{statusCode:400,body:JSON.stringify({message:'URL inválida'})})}if(p==='/')p='/index.html';const f=path.resolve(ROOT,'.'+p);if(!f.startsWith(path.resolve(ROOT)+path.sep))return send(res,{statusCode:403,body:JSON.stringify({message:'Acesso negado'})});fs.stat(f,(e,st)=>{if(e||!st.isFile())return send(res,{statusCode:404,body:JSON.stringify({message:'Arquivo não encontrado'})});const ext=path.extname(f).toLowerCase();res.writeHead(200,{'Content-Type':MIME[ext]||'application/octet-stream','Cache-Control':ext==='.html'?'no-cache':'public, max-age=86400'});fs.createReadStream(f).pipe(res);});}
http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);try{if(url.pathname==='/api/bling')return invoke('bling',req,res,url);if(url.pathname==='/api/checkout')return invoke('checkout',req,res,url);if(url.pathname==='/api/shipping')return invoke('shipping',req,res,url);if(url.pathname==='/api/bling-homologacao')return invoke('homologacao',req,res,url);if(url.pathname==='/api/health'){res.writeHead(200,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});return res.end(JSON.stringify({ok:true,service:'Relpps Render'}));}return stat(req,res,url);}catch(e){console.error(e);send(res,{statusCode:500,body:JSON.stringify({message:e.message||'Erro interno'})});}}).listen(PORT,HOST,()=>console.log(`Relpps Render listening on ${HOST}:${PORT}`));
